### Create a loan
POST {{BASE_URL}}/api/loan
partner-secret: 'partner-blue'
Content-Type: application/json

{
  "principal_amount": 20000,
  "term_months": 12,
  "collateral": {
    "brand": "Toyota",
    "model": "Camry",
    "manufacturing_year": 2022
  },
  "customer": {
    "name": "Clark Kent",
    "birth_date": "24-11-2004",
    "monthly_income": 4500,
    "id_number": "7482-4889"
  }
}

### Get loan by id
GET {{BASE_URL}}/api/loan?loan_id=62110039-6c6a-4acc-b502-4d0508411c25
partner-secret: 'partner-blue'